# Site settings
title: Dtow's Coding Blog
header-img: img/home-bg.png
email: djt4xe@virginia.edu
copyright_name: dtow55
description: > # this means to ignore newlines until "baseurl:"
  Helpful bits of knowledge on the path to becoming a software developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dtow55
learn_profile: dtow55
email_username: djt4xe@virginia.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
